language: c++

sudo: required
dist: trusty

cache:
  apt: true
  ccache: true

env:
  global:
    - MAKEFLAGS="-j4"

matrix:
  include:
    - os: osx
      env:
        - RECIPE="clang-64-debug"

script:
  - python2 ./scripts/check_build_sanity.py -r $RECIPE
